### ISSUE TITLE
Segmentation fault after generalized_biffing installed

### ISSUE THREAD

**Issue by ddska** [Spellhold-Studios/Generalized-Biffing#10] opened 2021-09-08 13:19 UTC
I installed the Planescape: Torment Enhanced Edition 3.1.4.0 from GOG.
The game is playable, everything works.

Then I installed the [BagsOfTorment](https://github.com/Argent77/A7-BagsOfTorment) mod using WeiDU (`weinstall` command).

It created new files in the `game/override` directory.

The game still playable, everything works.

After that I installed the generalized_biffing mod, also with `weinstall`, and choose option `2] Biff all files`. It created a new file with the name `tb#gen0.bif` in the `game/data` directory.

After that, when I run the game, I get the following error: `3708141 Segmentation fault      (core dumped) ./"Torment64"`

I've tried generalized_biffing versions 2.4 and 2.5.

I've tried WeiDU versions 246 and 247.

OS: Ubuntu 20.04
Kernel: Linux 5.11.0-25-generic #27~20.04.1-Ubuntu SMP Tue Jul 13 17:41:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ddska** [comment] 2021-09-08 13:20
Attaching the debug log.
[setup-generalized_biffing.debug.txt](https://github.com/SpellholdStudios/generalized_biffing/files/7129103/setup-generalized_biffing.debug.txt)

**Comment by jarnomikkola1** [comment] 2024-10-08 20:20
> Attaching the debug log. [setup-generalized_biffing.debug.txt](https://github.com/SpellholdStudios/generalized_biffing/files/7129103/setup-generalized_biffing.debug.txt)

You are trying to install this to a Enhanced Edition game. You shouldn't. There is no need, the new engine doesn't benefit from it at all...

**Comment by Argent77** [comment] 2024-10-08 20:52
> > Attaching the debug log. [setup-generalized_biffing.debug.txt](https://github.com/SpellholdStudios/generalized_biffing/files/7129103/setup-generalized_biffing.debug.txt)
> 
> You are trying to install this to a Enhanced Edition game. You shouldn't. There is no need, the new engine doesn't benefit from it at all... at least to what knowledge the community had some time ago.

That's not true. PST:EE contains a game-breaking bug that occurs in modded games which can be worked around by installing Generalized Biffing.

Quote from [this topic](http://www.shsforums.net/topic/59645-pst-ub-reloaded-a-continuation-of-qwinns-pst-ub-for-pstee/?p=599277):
> **Important:** The current patch version of PST:EE (v3.1.3) contains a bug that resets content, such as stores or areas, when you enter the Modron Maze. To work around this issue, it is strongly recommended to download and install [Generalized Biffing](http://www.shsforums.net/files/file/741-generalized-biffing/) as the final mod in the mod list.

**Comment by skellytz** [comment] 2024-10-16 18:31
Has anyone been able to reproduce this? Were there any confirmed issues like that with OCaml on Linux back then (WeiDU v246 and v247)?

**Comment by Argent77** [comment] 2024-10-16 19:54
I couldn't reproduce this issue. PST:EE and other EE games still worked fine after installing Generalized Biffing with the aforementioned WeiDU versions in my tests.

Linux distros can differ quite a bit in library setups and kernel configurations, however, so I wouldn't completely rule out local issues under certain conditions. That is beyond the control of this mod though. I recommend to close this issue.

**Closed** 2024-10-17 23:57 UTC
Labels: question
